FROM openjdk:12
VOLUME /tmp
ADD ./target/springboot-servicio-usuarios-commons-0.0.1-SNAPSHOT.jar springboot-servicio-usuarios-commons.jar
ENTRYPOINT ["java","-jar","/springboot-servicio-usuarios-commons.jar"]